# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm"
    commit-message:
      prefix: "chore: "
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/example"
    commit-message:
      prefix: "chore: "
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    directory: "/"
    commit-message:
      prefix: "chore: "
    schedule:
      interval: "weekly"
